# Generated by Django 5.2.8 on 2025-11-21 12:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id_planta', models.AutoField(primary_key=True, serialize=False)),
                ('nome_popular', models.CharField(blank=True, max_length=40, null=True)),
                ('tipo', models.CharField(blank=True, max_length=40, null=True)),
                ('origem', models.CharField(blank=True, max_length=80, null=True)),
                ('familia', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('imagem', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'plantas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('senha', models.CharField(max_length=15)),
                ('localizacao', models.CharField(blank=True, max_length=100, null=True)),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id_imagem', models.AutoField(primary_key=True, serialize=False)),
                ('url_imagem', models.CharField(max_length=150)),
                ('id_planta', models.ForeignKey(db_column='id_planta', on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='main.planta')),
            ],
            options={
                'db_table': 'imagens',
            },
        ),
        migrations.CreateModel(
            name='Troca',
            fields=[
                ('id_troca', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='main.usuario')),
            ],
            options={
                'db_table': 'trocas',
            },
        ),
        migrations.AddField(
            model_name='planta',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='main.usuario'),
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id_chat', models.AutoField(primary_key=True, serialize=False)),
                ('mensagem', models.TextField()),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='main.usuario')),
            ],
            options={
                'db_table': 'mensagens',
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id_avaliacao', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('id_avaliado', models.ForeignKey(db_column='id_avaliado', on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_recebidas', to='main.usuario')),
                ('id_avaliador', models.ForeignKey(db_column='id_avaliador', on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_feitas', to='main.usuario')),
            ],
            options={
                'db_table': 'avaliacao',
            },
        ),
    ]
