# Generated by Django 5.2.8 on 2025-11-25 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_usuario_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True},
        ),
        migrations.RenameField(
            model_name='avaliacao',
            old_name='id_avaliado',
            new_name='avaliado',
        ),
        migrations.RenameField(
            model_name='avaliacao',
            old_name='id_avaliador',
            new_name='avaliador',
        ),
        migrations.RenameField(
            model_name='mensagem',
            old_name='id_usuario',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='troca',
            old_name='id_usuario',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='imagem',
            name='id_planta',
        ),
        migrations.RemoveField(
            model_name='planta',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='imagem',
            name='planta',
            field=models.ForeignKey(db_column='id_planta', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imagens_extra', to='main.planta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planta',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plantas', to='main.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='url_imagem',
            field=models.ImageField(max_length=150, upload_to='detalhes/'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='data_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='planta',
            name='imagem',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to='plantas/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=40),
        ),
    ]
